import ProjectDescription

let workspace = Workspace(
    name: "Workspace",
    projects: [
        "AllInOneUnitTests",
        "App",
        "LibraryA",
        "LibraryB",
        "Features/**"
    ],
    schemes: [.allInOneTests],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)

public extension Scheme {
  static let allInOneTests = Scheme(
    name: "AllInOneTests",
    shared: true,
    hidden: false,
    buildAction: BuildAction(
      targets: [
        .project(path: "AllInOneUnitTests", target: "AllInOneUnitTests"),
        .project(path: "App", target: "AppTests"),
      ]
    ),
    testAction: TestAction.targets(
      [
        TestableTarget(target: .project(path: "AllInOneUnitTests", target: "AllInOneUnitTests")),
        TestableTarget(target: .project(path: "App", target: "AppTests")),
      ]
    ),
    runAction: RunAction.runAction(
      executable: .project(path: "App", target: "App")
    ),
    archiveAction: nil,
    profileAction: nil,
    analyzeAction: nil
  )
}
